In [1]:
import pandas as pd
import numpy as np

print("All imports successful!")

All imports successful!

In [2]:
fam = ["Dad", "Delta", "Brooke", "Clebo", "Liam", "Henry", "DODO"]
print(f"{fam}\n")
print(fam.pop())

['Dad', 'Delta', 'Brooke', 'Clebo', 'Liam', 'Henry', 'DODO']

DODO

In [3]:
fam.pop()
print(fam)

['Dad', 'Delta', 'Brooke', 'Clebo', 'Liam']

In [4]:
nums = []
for i in list(range(1,15)):
    if i % 2 == 0:
        nums.append(i)
print(nums)

[2, 4, 6, 8, 10, 12, 14]

In [5]:
df = pd.read_csv('../../data/raw/shopping_trends.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df[df['Purchase Amount (USD)']>50]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,L,Indigo,Summer,3.5,No,Bank Transfer,Standard,No,No,5,PayPal,Fortnightly
3893,3894,21,Female,Hat,Accessories,64,Massachusetts,L,White,Fall,3.3,No,Bank Transfer,Store Pickup,No,No,29,Bank Transfer,Bi-Weekly
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,L,White,Spring,3.9,No,Cash,2-Day Shipping,No,No,44,Credit Card,Every 3 Months
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df.shape

(3900, 19)

In [8]:
df[df['Purchase Amount (USD)']>80]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Credit Card,Store Pickup,Yes,Yes,8,PayPal,Monthly
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Venmo,Standard,Yes,Yes,46,Debit Card,Bi-Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3882,3883,35,Female,Pants,Clothing,95,North Dakota,L,Blue,Fall,2.6,No,Credit Card,Free Shipping,No,No,24,Cash,Fortnightly
3886,3887,37,Female,Jewelry,Accessories,92,Iowa,S,Brown,Summer,3.9,No,Bank Transfer,Express,No,No,40,Debit Card,Quarterly
3890,3891,35,Female,Shirt,Clothing,81,Nebraska,XL,Green,Winter,2.6,No,Credit Card,Standard,No,No,33,Debit Card,Annually
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,L,Indigo,Summer,3.5,No,Bank Transfer,Standard,No,No,5,PayPal,Fortnightly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,No,33,Venmo,Quarterly

In [9]:
df[df['Purchase Amount (USD)']>98]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
42,43,20,Male,Coat,Outerwear,100,Tennessee,M,Beige,Spring,4.1,Yes,Bank Transfer,Free Shipping,Yes,Yes,15,PayPal,Annually
91,92,44,Male,Scarf,Accessories,99,South Carolina,S,Green,Winter,4.6,Yes,PayPal,Standard,Yes,Yes,18,Credit Card,Every 3 Months
95,96,37,Male,Sneakers,Footwear,100,Missouri,L,Pink,Fall,3.8,Yes,PayPal,Free Shipping,Yes,Yes,48,PayPal,Monthly
193,194,36,Male,Belt,Accessories,100,North Dakota,S,Silver,Fall,3.0,Yes,PayPal,Standard,Yes,Yes,29,Venmo,Annually
204,205,24,Male,Sneakers,Footwear,100,Arizona,M,Yellow,Fall,4.0,Yes,PayPal,Store Pickup,Yes,Yes,35,Cash,Bi-Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3746,3747,53,Female,Coat,Outerwear,99,Idaho,XL,Cyan,Summer,2.6,No,Debit Card,Next Day Air,No,No,49,PayPal,Monthly
3781,3782,52,Female,Boots,Footwear,99,Tennessee,M,Pink,Winter,3.7,No,Venmo,Standard,No,No,40,PayPal,Fortnightly
3819,3820,36,Female,Pants,Clothing,99,Arkansas,S,Gold,Spring,2.9,No,PayPal,Express,No,No,45,Cash,Quarterly
3837,3838,45,Female,Hoodie,Clothing,100,New Mexico,M,Green,Spring,4.8,No,Debit Card,Free Shipping,No,No,33,Bank Transfer,Fortnightly
3864,3865,55,Female,T-shirt,Clothing,99,Wyoming,S,Blue,Winter,4.9,No,Bank Transfer,Express,No,No,1,Debit Card,Fortnightly

In [11]:
what_is_fam = [42, 21, 20, 16, 14, 12]

fam_total = 0

for i in what_is_fam:
    fam_total += i
print(fam_total)

125